package com.csye6225.lab.ziyao.program.DAO;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "announcement")
public class Announcement {
    int id;
    int annoucementId;
    int boardId;
    String annoucementText;

    public Announcement() {

    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "announcementId", globalSecondaryIndexName = "idx_announcementId")
    public int getAnnoucementId() {
        return annoucementId;
    }

    public void setAnnoucementId(int annoucementId) {
        this.annoucementId = annoucementId;
    }

    @DynamoDBRangeKey(attributeName = "boardId")
    public int getBoardId() {
        return boardId;
    }

    public void setBoardId(int boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "text")
    public String getAnnoucementText() {
        return annoucementText;
    }

    public void setAnnoucementText(String annoucementText) {
        this.annoucementText = annoucementText;
    }
}
