package com.csye6225.lab.ziyao.program.DAO;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "board")
public class Board {
    int id;
    int boardId;
    int courseId;
    public Board() {

    }
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "boardId", globalSecondaryIndexName = "idx_boardId")
    public int getBoardId() {
        return boardId;
    }

    public void setBoardId(int boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "courseId")
    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
}
