package com.csye6225.lab.ziyao.program.DAO;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.csye6225.lab.ziyao.people.DAO.Professor;
import com.csye6225.lab.ziyao.people.DAO.Student;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

@DynamoDBTable(tableName = "course")
public class Course {
    String id;
    String courseId;
    String professorId;
    String TAId;
    String department;
    String boardId;
    List<String> registeredStudentList;
    String courseName;
    String topicArn;

    public Course(String courseName){
        this.courseName = courseName;
        registeredStudentList = new ArrayList<>();
    }
    public Course() {
        registeredStudentList = new ArrayList<>();
    }

    @DynamoDBAttribute(attributeName = "courseName")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "idx_courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "TAId")
    public String getTAId() {
        return TAId;
    }

    public void setTAId(String TAId) {
        this.TAId = TAId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

//    @DynamoDBAttribute(attributeName = "studentList")
    @DynamoDBIgnore
    public List<String> getRegisteredStudentList() {
        return registeredStudentList;
    }

    public void setRegisteredStudentList(List<String> registeredStudentList) {
        this.registeredStudentList = registeredStudentList;
    }

    @DynamoDBAttribute(attributeName = "topicArn")
    public String getTopicArn() {
        return topicArn;
    }

    public void setTopicArn(String topicArn) {
        this.topicArn = topicArn;
    }
}
