package com.csye6225.lab.ziyao.program.DAO;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.csye6225.lab.ziyao.people.DAO.Professor;
import com.csye6225.lab.ziyao.people.DAO.Student;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

@DynamoDBTable(tableName = "course")
public class Course {
    int id;
    int courseId;
    int professorId;
    int TAId;
    String department;
    int boardId;
    List<Integer> registeredStudentList;
    String courseName;

    public Course(String courseName){
        this.courseName = courseName;
        registeredStudentList = new ArrayList<>();
    }
    public Course() {
        registeredStudentList = new ArrayList<>();
    }

    @DynamoDBAttribute(attributeName = "courseName")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "courseId", globalSecondaryIndexName = "idx_courseId")
    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public int getProfessorId() {
        return professorId;
    }

    public void setProfessorId(int professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "TAId")
    public int getTAId() {
        return TAId;
    }

    public void setTAId(int TAId) {
        this.TAId = TAId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public int getBoardId() {
        return boardId;
    }

    public void setBoardId(int boardId) {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "studentList")
    public List<Integer> getRegisteredStudentList() {
        return registeredStudentList;
    }

    public void setRegisteredStudentList(List<Integer> registeredStudentList) {
        this.registeredStudentList = registeredStudentList;
    }
}
