package com.csye6225.lab.ziyao.people.DAO;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.xml.bind.annotation.XmlRootElement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;


@DynamoDBTable(tableName = "professor")
public class Professor extends People{
    private String department;
    private String professorId;

    public Professor(){

    }


    public Professor(String professorId, String firstName, String lastName, String department, Date joingDate){
        super(firstName, lastName, joingDate, professorId);
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @DynamoDBAttribute(attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(attributeName = "professorId", globalSecondaryIndexName = "idx_professorId")
    public String getProfessorId() {
        return this.professorId;
    }
    public void setProfessorId(String id) {
        this.professorId = id;
    }


    @DynamoDBAttribute(attributeName = "registerDate")
    public String getRegisterStringDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return sdf.format(this.registerDate);
    }
    public void setRegisterStringDate(String date) throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        this.registerDate = sdf.parse(date);
    }


    @DynamoDBIgnore
    @Override
    public String toString() {
        return "ProfId=" + getProfessorId() + ", firstName=" + getFirstName() + ", department=" + getDepartment() + ",joiningDate=" + getRegisterDate();
    }
}
